// Zaawansowane_programowanie_internetowe/react-app/src/Components/UpdatePersonForm.tsx
import React, {useState} from "react";
import { useNavigate, Link } from "react-router-dom";

const UpdatePersonForm = () =>{

    const [person, setPerson] = useState({
        id: '',
        firstName: '',
        lastName: '',
        dateOfBirth: new Date(),
        origin: '',
    })

    const navigate = useNavigate()

    const handleSubmit = async(e: React.FormEvent) =>{
        e.preventDefault()

        const response = await fetch(`http://localhost:5147/PersonUpdate/${person.id}`,{
            method: "PUT",
            headers:{
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                ...person,
                dateOfBirth: new Date(person.dateOfBirth)
            })
        })

        if(response.ok){
            navigate('/')
        }
    }

    return(
        <>
            <h1>Edytuj dane o osobie!</h1>
            <form onSubmit={handleSubmit} className="PersonForm">

                <label>
                    Wprowadź id: <br></br>
                    <input 
                        type="text" 
                        value={person.id}
                        onChange={(e)=>setPerson({...person, id: e.target.value})}
                        placeholder="Id"
                    />
                </label>

               <label>
                    Wprowadź imię osoby: <br></br>
                    <input 
                        type="text" 
                        value={person.firstName}
                        onChange={(e)=>setPerson({...person, firstName: e.target.value})}
                        placeholder="Imię"
                    />
               </label>

                <label>
                    Wporwadź nazwisko osoby: <br></br>
                    <input 
                        type="text" 
                        value={person.lastName}
                        onChange={(e)=>setPerson({...person, lastName: e.target.value})}
                        placeholder="Nazwisko"
                    />
                </label>

                <label>
                    Wprowadź date urodzenia: <br></br>
                    <input 
                        type="text" 
                        value={person.dateOfBirth.toISOString().split("T")[0]}
                        onChange={(e)=>setPerson({...person, dateOfBirth: new Date(e.target.value)})}
                        placeholder="Data urodzenia"
                    />
                </label>

                <label>
                    Wprowadź kraj pochodzenia osoby: <br></br>
                    <input 
                        type="text" 
                        value={person.origin}
                        onChange={(e)=>setPerson({...person, origin: e.target.value})}
                        placeholder="Pochodzenie"
                    />
                </label>

                <button type="submit">Edytuj</button>
            </form>
            
            <div className="backLink">
                <Link to="/">Wróć do strony głównej</Link>
            </div>
        </>
    )

}

export default UpdatePersonForm

// Zaawansowane_programowanie_internetowe/angular-app/src/app/update-person-form/update-person-form.component.ts
import { Component } from '@angular/core';
import { PersonService } from '../person.service';

@Component({
  selector: 'app-update-person-form',
  templateUrl: './update-person-form.component.html',
  styleUrls: ['./update-person-form.component.css'],
})
export class UpdatePersonFormComponent {

  person={
    id: null,
    firstName: '',
    lastName: '',
    dateOfBirth: '',
    origin: '',
  }

  constructor(private personService:PersonService){}

  onSubmit(){
    if(this.person.id){
      this.personService.updatePerson(this.person.id, this.person).subscribe({
        next: (result) =>{
          window.location.href='/';
        }
      });
    }
  }
}

<h1>Edycja osoby!</h1>
<form (ngSubmit)="onSubmit()" class="PersonForm">
    <label for="id">Id:</label>
    <input 
        type="number"
        id="id"
        [(ngModel)]="person.id"
        name="id"
        placeholder="Id"
    />

    <label for="firstName">Imię:</label>
    <input 
        type="text"
        id="firstname"
        [(ngModel)]="person.firstName"
        name="firstname"
        placeholder="Imię"
    />

    <label for="lastName">Nazwisko:</label>
    <input 
        type="text"
        id="lastName"
        [(ngModel)]="person.lastName"
        name="lastName"
        placeholder="Nazwisko"
    />

    <label for="dateOfBirth">Data urodzenia:</label>
    <input 
        type="date"
        id="dateOfBirth"
        [(ngModel)]="person.dateOfBirth"
        name="dateOfBirth"
    />

    <label for="origin">Pochodzenie:</label>
    <input 
        type="text"
        id="origin"
        [(ngModel)]="person.origin"
        name="origin"
        placeholder="Pochodzenie"
    />

    <button type="submit">Dodaj</button>
</form>

<div class="menu">
    <a routerLink="/">Wróć do strony głównej</a>
</div>
