// Zaawansowane_programowanie_internetowe/angular-app/src/app/person-list/person-list.component.ts
import { Component, OnInit } from '@angular/core';
import { PersonService } from '../person.service';

@Component({
  selector: 'app-person-list',
  templateUrl: './person-list.component.html',
  styleUrls: ['./person-list.component.css'],
})
export class PersonListComponent implements OnInit{

  people: any []=[]

  constructor(private personService:PersonService){}

  ngOnInit(): void {
    this.personService.getPeople().subscribe((data)=>{
      this.people=data;
    });
  }

}

<h1>Tabela osób!</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>DateOfBirth</th>
            <th>Origin</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let person of people">
            <td>{{person.id}}</td>
            <td>{{person.firstName}}</td>
            <td>{{person.lastName}}</td>
            <td>{{person.dateOfBirth | date}}</td>
            <td>{{person.origin}}</td>
        </tr>
    </tbody>
</table>

<div class="menu">
    <a routerLink="/add">Dodaj</a>
    <a routerLink="/update">Edytuj</a>
    <a routerLink="/delete">Usuń</a>
</div>

// Zaawansowane_programowanie_internetowe/react-app/src/Components/PersonList.tsx
import React, {useEffect, useState} from "react";
import { Link } from "react-router-dom";
import PersonItem from "./PersonItem";
import './Style.css';

interface Person
{
    id: number,
    firstName: string,
    lastName: string,
    dateOfBirth: Date,
    origin: string,
}

const PersonList = () =>{
    const [people, setPeople] = useState<Person[]>([])

    useEffect(()=>{
        const fetchData = async() =>{
            try{
                const response = await fetch('http://localhost:5147/GetPeople')
                const data: Person[] = await response.json()
                setPeople(data)
            }catch(err){
                console.error(err)
            }
        }

        fetchData()
    },[])

    return(
        <>
            <nav className="menu">
                <Link to="/add">Dodaj</Link>
                <Link to="/update">Edytuj</Link>
                <Link to="/delete">Usuń</Link>
            </nav>
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>FirstName</th>
                        <th>LastName</th>
                        <th>DateOfBirth</th>
                        <th>Origin</th>
                    </tr>
                </thead>
                <tbody>
                    {people.map((person)=>(
                        <PersonItem key={person.id} {...person}/>
                    ))}
                </tbody>
            </table>
        </>
    )
}

export default PersonList
